### PR TITLE
added docs, barycentric correction and shorter version of s3_reduce.py

### PR DESCRIPTION
**Pull request by sebastian-zieba**
- Added **docs** including a Jupyter Notebook (docs/source/intro.ipynb) going through the basics of data reduction, JWST NIRCam data and Eureka! The requirements.txt also includes nbsphinx now which is needed to embed Jupyter Notebooks on Read The Docs.

- Added a script (eureka/lib/barycorr.py) that automatically downloads the horizons file from JPL Horizons for the **barycentric correction**. The code is accessed when running s3_reduce.py and furthermore needs eureka/lib/suntimecorr.py and eureka/lib/splinterp.py. 

- Added a **shorter version of s3_reduce.py** called eureka/S3_data_reduction/s3_reduce_short.py. Several functions have been moved into a new file called eureka/lib/util.py for that. Plotting functions have been from s3_reduce_short.py to eureka/lib/plots_s3.py.

### CODE REVIEW

**Comment by kevin218** [comment]
As it turns out, the FITS files include BJD_TDB values so I'm not sure we need barycorr.py or it's associated files.
For consistency, let's put the S3_plots.py file in the S3 directory.

**Review by kevin218 — COMMENTED** [review]
In addition to my previous comments...
- Remove .ecf files from commit
- Remove .png files from commit
- In index.rst and installation.rst, add "!" add end of Eureka
- savetable.py needs some documentation

**Comment by kevin218** [comment]
Final thought...  I'm fine with you updating S3_reduce.py directly instead of creating a separate 'short' version.  The code clean up that you've done here was necessary.

**Comment by sebastian-zieba** [comment]
> As it turns out, the FITS files include BJD_TDB values so I'm not sure we need barycorr.py or it's associated files.

Yeah, I noticed that the timestaps in 'INT_TIMES' include MJD and BJD but they are currently exactly the same. Eg for one of the integrations: 
('integration_number', 'int_start_MJD_UTC', 'int_mid_MJD_UTC', 'int_end_MJD_UTC', 'int_start_BJD_TDB', 'int_mid_BJD_TDB', 'int_end_BJD_TDB')
(1281, 59694.2034325971, 59694.20347004844, 59694.20350749977, 59694.2034325971, 59694.20347004844, 59694.20350749977)

So I guess that will be fixed at some point and we won't need any barycentric correction?

**Comment by kevin218** [comment]
> So I guess that will be fixed at some point and we won't need any barycentric correction?

Yes, it is only the same because we're using simulated data.

**Review by kevin218 — APPROVED** [review]

**Pull request merged**
