### PR TITLE
Resolve issue with blank int_times + fix NIRspec disp axis trimming

### PR DESCRIPTION
**Pull request by AarynnCarter**
Quick fix for issue #396

Haven't had the time to *fully* check this through Stage 3 yet, but I can see that the INT_TIMES is correctly populated after Stage 1. Will take a proper look tomorrow but wanted to put the PR in anyway.

### CODE REVIEW

**Comment by jbrande** [comment]
I'm not sure this has resolved the issue, I'm still getting the same error as Erin after pulling your dev branch. For what it's worth, I'm trying this on Everett's minified NIRSpec data.

**Comment by AarynnCarter** [comment]
@jbrande, I'm checking things over now, hopefully I can report back at some point today. I don't think Everett's minified data will work as the INT_TIMES for that file gets populated with 3200 values (i.e. the size of the untrimmed seg004 file)

**Comment by AarynnCarter** [comment]
Okay I can confirm that with this PR, in combination with Erin's #395, Eureka! will run from Stage 1 through Stage 3 on one segment of the PRISM data.

**Comment by jbrande** [comment]
> @jbrande, I'm checking things over now, hopefully I can report back at some point today. I don't think Everett's minified data will work as the INT_TIMES for that file gets populated with 3200 values (i.e. the size of the untrimmed seg004 file)

Ah, yeah. That would do it.

**Comment by AarynnCarter** [comment]
Finally found a fix for the really annoying dispersion axis trimming that the jwst pipeline does to the NIRSpec PRISM data -  now we have the full 512x32 array. It works similarly to the custom ramp fitting routines, by temporarily swapping out one of the pipeline functions for a duplicate with the desired wavelength range trimming. 

@taylorbell57, can't figure out the Flake8 indenting rules, leaving it for now...

**Review by kevin218 — APPROVED** [review]

**Pull request merged**
