### PR TITLE
Implementation of an S2 pipeline step

### PR DESCRIPTION
**Pull request by taylorbell57**
I have now implemented a functional S2 pipeline step (addressing Issue #60) which can be interacted with following behaviours similar to Eureka's S3. I have permitted only a limited number of tweaks to the S2 pipeline steps, but in the future we can replace entire steps or do other, more complicated, things quite easily using this framework (a wrapper for the Spec2Pipeline class from jwst.pipeline.calwebb_spec2).

I have made it possible to sequentially run S2 and S3 using the run_eureka.py file or to run S2 and S3 independently, and you can still use the S2 outputs from the JWST pipeline as well. If you are not running S2 and S3 sequentially, your S3 ecf file must specify the exact folder that contains the stage 2 outputs you want to analyze. Meanwhile, if you want to run S2 and S3 sequentially, you don't need to tell the S3 ecf file the exact folder that the S2 outputs will be inserted into as this will be passed through the metadata object.

I also made some changes to the util.py file and the S3 ecf file which now allows the outputs of Eureka to be stored somewhere outside of the eureka project directory. This is important if you want to have one drive with your code on it and a separate drive for data.

This step has been thoroughly tested for MIRI and NIRSpec data on my laptop (Ubuntu 20.04) using Python 3.9.5 and the minimum requirements as specified in the requirements.txt file (which I had to update). @AarynnCarter, if you want to test Eureka's S2+S3 on NIRSpec data, can you git pull my branch onto your computer and try running it yourself? I tried again myself with the full 2.7 GB file and it still overflows my 12 GB of RAM (can't be a bug on our end - STScI just wrote some RAM intensive code). I have yet to write any unit tests as I am waiting for Giannina to push her examples for S3 so that I have a good understanding of the format we want these tests to have. I can either write the S2 unit tests before or after this pull request is approved.

This pull request also resolves one issue with MIRI observations as noted in Issue #36. As it stands, S4 is broken due to the changes in how the S3 outputs are saved now that a range of apertures are permitted (Issue #40). This pull request does not fix that issue, but it is the thing I plan to tackle next.

### CODE REVIEW

**Comment by taylorbell57** [comment]
Good catch, just fixed that!

**Comment by AarynnCarter** [comment]
Okay, so I managed to run things through on my laptop today and I think it got 99% of the way through before it crashed with the following error during the plotting. I haven't had the chance to look at it properly as I'm signing off for the day, but thought I'd paste it here in case you have a moment to take a look before me. 

```
Generating x1dints figure
Traceback (most recent call last):
  File "/Users/acarter/Documents/TRANSITS/EUREKA/TESTING_TAYLOR/run_eureka.py", line 12, in <module>
    s2_meta = s2.run_eurekaS2(eventlabel)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 164, in run_eurekaS2
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/pyplot.py", line 966, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/figure.py", line 3015, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
    self.figure.draw(renderer)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/figure.py", line 2790, in draw
    mimage._draw_list_compositing_images(
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2881, in draw
    self._update_title_position(renderer)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2822, in _update_title_position
    if title.get_window_extent(renderer).ymin < top:
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/text.py", line 903, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/text.py", line 306, in _get_layout
    _, lp_h, lp_d = renderer.get_text_width_height_descent(
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 229, in get_text_width_height_descent
    w, h, d = texmanager.get_text_width_height_descent(
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/texmanager.py", line 399, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/texmanager.py", line 291, in make_dvi
    self._run_checked_subprocess(
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/matplotlib/texmanager.py", line 268, in _run_checked_subprocess
    _log.debug(report)
  File "/Users/acarter/anaconda3/envs/eureka_tjb/lib/python3.9/site-packages/jwst/associations/lib/log_config.py", line 158, in log
    for line in msg.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```

**Comment by taylorbell57** [comment]
Well that is definitely a strange error message... It looks like its a TeX issue which is strange because I didn't even do anything fancy (just plain text axis labels - no symbols or anything). My guess is that this is related to your earlier issues with TeX when you were trying to run S3. Can you test whether you can do any plotting whatsoever by importing eureka and pyplot into ipython or a Jupyter notebook and making a simple little test plot to see if you get the same issue.

**Comment by AarynnCarter** [comment]
Here I go again haha, I'll take a look and get back to you.

**Comment by kevin218** [comment]
Without having tested the changes, the code itself looks good.  I'll let Aarynn give final approval once he's able to run it through.

**Pull request merged**
