### PR TITLE
Added tiny NIRISS dataset

### PR DESCRIPTION
**Pull request by lpcoulombe**
Added stage 1 outputs of a tiny NIRISS dataset (3 integrations) in Eureka/tests/data/JWST-Sim/NIRISS/Stage1 .

### CODE REVIEW

**Review by kevin218 — APPROVED** [review]

**Comment by kevin218** [comment]
I just realized these are `rampfitstep` files, but we need `rateints` files.

**Comment by lpcoulombe** [comment]
The rampfitstep files are indeed the `rateints` and `rate` files. I have not ran the tiny dataset through stage 2 but I can do it in the next few days. I will change the files' position at the same time.

**Comment by taylorbell57** [comment]
The files are in the correct location, but I am confused about why there are two files and why they have rampfitstep suffixes rather than rateints. Is this just how NIRISS files get processed by the `jwst` pipeline?

**Comment by kevin218** [comment]
Yes, NIRISS is a rebel that doesn't like to follow the rules, thus making our lives more difficult.
The first file appears to contain a single integration, which breaks the pipeline, while the second contains 3 integrations.  
As far as I can tell, there's no reason to have Eureka/eureka/tests, which is where I found the files.

**Comment by taylorbell57** [comment]
Ah indeed, I misread the path in the Files Changed section on the PR

**Pull request merged**
