### PR TITLE
Moving meta.scandir to data.scandir for WFC3 data

### LINKED ISSUE #601: [Bug]:Manual Clipping in Shared Fitting of White Light Curves -- Not Working for WFC3
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Light curve fitting (Stages 4-6)

### What happened?

I'm using Eureka to perform joint white light curve fitting of several transits simultaneously (HST WFC3 Observations). When I manual_clip list set to anything other than None, the program crashes. 

White the data in the lc object gets clipped as it should, the corresponding data points in meta.scandir arent being clipped. 
I attempted fixing this myself, but then clipping even a single data point caused the fitting to go berserk.

Can somebody please help fix this issue with the manual clipping in shared white light curve fitting?

### Error traceback output

{
	"name": "IndexError",
	"message": "boolean index did not match indexed array along dimension 0; dimension is 87 but corresponding boolean dimension is 88",
	"stack": "---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[6], line 3
      1 if __name__ == '__main__':
      2     # s5_meta = s5.fitlc(eventlabel, ecf_path=ecf_path, s4_meta=s4_meta)
----> 3     s5_meta = s5.fitlc(eventlabel, ecf_path=ecf_path, s4_meta=None)  # Shared
      4     # s6_meta = s6.plot_spectra(eventlabel, ecf_path=ecf_path, s5_meta=s5_meta)

File ~/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/S5_lightcurve_fitting/s5_fit.py:211, in fitlc(eventlabel, ecf_path, s4_meta, input_meta)
    208 if meta.multwhite:
    209     for p in range(len(meta.inputdirlist)+1):
    210         meta, lc_whites[p], log = \\
--> 211             util.manual_clip(lc_whites[p], meta, log)
    212         meta.nints[p] = len(lc_whites[p].time.values)
    213 else:

File ~/miniconda3/envs/eureka/lib/python3.9/site-packages/eureka/lib/util.py:154, in manual_clip(lc, meta, log)
    152 lc = lc.isel(time=time_inds)
    153 if hasattr(meta, 'scandir'):
--> 154     meta.scandir = meta.scandir[time_bool[::meta.nreads]]
    156 return meta, lc, log

IndexError: boolean index did not match indexed array along dimension 0; dimension is 87 but corresponding boolean dimension is 88"
}

### What operating system are you using?

_No response_

### What version of Python are you running?

_No response_

### What Python packages do you have installed?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by taylorbell57**
This hopefully resolves #601

Storing the scandir values in meta is a pain since they don't get treated in the same way as the other data (e.g., manual clipping needs to separately be applied to the meta variable). These values were already being stored in the data/spec/lc variables, so now I exclusively use those wherever possible.

I know that the tests all pass (at least on my machine), but I don't know if I messed anything up along the way and don't have a quick and easy WFC3 dataset that I can test this on. If @kevin218 or @astroRez can test these edits out on some real data, that'd be really helpful

### CODE REVIEW

**Comment by taylorbell57** [comment]
Alright, I implemented a patch for that first error you encountered. As for the `ValueError: operands could not be`... error, those three array lengths are not individual lightcurves. It is saying that the model should be 171 integrations long but the model was 3x too long for some reason. I've merged in recent commits to the main branch in the hopes that'll help, but if it doesn't resolve the issue, can do add a `print(component.name)` in the line just above where it crashed so that we can at least know which of the models is the one returning an array of the wrong shape. I suspect you're right that it's probably the `HSTRampModel`, but it'd be nice to confirm that since a cursory glance at that model doesn't show any obvious issues

**Review by kevin218 — COMMENTED** [review]
The changes look good to me, but I'll let Reza test them on some HST data before approving.

**Comment by kevin218** [comment]
The issue that @astroRez is having with the three LCs should be solved in #609.  Essentially, Line 129 of HSTRampModel.py is using the wrong time variable.

**Comment by taylorbell57** [comment]
@kevin218, alright I'll try to review that PR today or on Monday

**Comment by taylorbell57** [comment]
@astroRez, alright the code in this PR should now solve all of the problems you mentioned - can you please test this on an HST dataset to make sure it all works well?

**Comment by astroRez** [comment]
Everything is working now, with the use of a workaround for one last identified bug! Exciting times!!

if multwhite == True, and if fixed parameters are used for the hstramp coefficients, it results in a kernel crash (no error message b/c its a kernel crash).
For now, I'm using Kevin's clever workaround of just setting very tight bounds and running them as free parameters. 
This seems to get the job done in the meantime, and I'm finally getting some spectra! woo!    

Thank you both for your help. I for one appreciate it a lot.

**Review by kevin218 — DISMISSED** [review]

**Comment by taylorbell57** [comment]
@kevin218, just had some merge conflicts to resolve and should be good to go for a final approval

**Review by kevin218 — APPROVED** [review]

**Pull request merged**
