### PR TITLE
fix manual clip bug in S5

### PR DESCRIPTION
**Pull request by lkreidberg**
this PR fixes a bug in S5 for manually clipping data points. The lc and meta arrays are now updated when the manual_clip function is called in s5_fit.py

### CODE REVIEW

**Comment by taylorbell57** [comment]
Out of curiosity, did this actually not work as is, or were you worried it wouldn't based on reading the code? I would've expected it to work just fine since python passes variables by reference into functions, so the functions are editing the original copies of the variables and we shouldn't need to return meta, lc, or log (but I have been just to help communicate to the reader that they've been changed). If this actually doesn't work as it is in the main branch, then we will need to do some careful checking elsewhere to make sure a similar bug isn't happening in other places

**Comment by lkreidberg** [comment]
it didn't work! I was surprised, because I also thought the variables should have been updated. Not sure what happened here, but after the explicit assignment everything was fine!

**Comment by sebastian-zieba** [comment]
Yeah, I had exactly the same problem like Laura

**Comment by taylorbell57** [comment]
Huh, that's super strange! Thanks for the patch!

**Review by taylorbell57 — APPROVED** [review]

**Pull request merged**
